import type { Models } from 'appwrite';
type DocumentData = Models.Document & Record<string, unknown>;
import { DATABASE_ID, ID, Query, databases } from './appwrite';
import type { ContentInput, NavigationLink, PortfolioContent, SiteSettings, SocialLink, YouTubeChannel } from '../types';

export const CONTENTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CONTENTS_COLLECTION_ID || 'portfolio_contents';
export const SETTINGS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SETTINGS_COLLECTION_ID || 'site_settings';
export const SOCIAL_LINKS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SOCIAL_LINKS_COLLECTION_ID || 'social_links';
export const NAVIGATION_LINKS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_NAVIGATION_LINKS_COLLECTION_ID || 'navigation_links';
export const YOUTUBE_CHANNELS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_YOUTUBE_CHANNELS_COLLECTION_ID || 'youtube_channels';
const SETTINGS_ID = 'site-settings';
const strings = (v: unknown): string[] => Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];
const optional = (v: unknown): string | undefined => typeof v === 'string' && v.trim() ? v : undefined;
export const defaultSiteSettings: SiteSettings = { brandName: 'Molvess', contactTitle: 'Bir Projen mi var? Konuşalım.', contactDescription: 'Video düzenleme, yazılım geliştirme ya da iş birliği için benimle iletişime geçebilirsin.', contactEmail: '', footerText: 'Tüm hakları saklıdır.' };
export const slugify = (value: string) => value.toLocaleLowerCase('tr-TR').replace(/[^a-z0-9ğüşıöç]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 90);
function mapContent(d: DocumentData): PortfolioContent { return { $id: d.$id, $createdAt: d.$createdAt, $updatedAt: d.$updatedAt, title: String(d.title || ''), slug: String(d.slug || d.$id), description: String(d.description || ''), shortDescription: optional(d.shortDescription), contentType: d.contentType as PortfolioContent['contentType'], sourceType: d.sourceType as PortfolioContent['sourceType'], sourceId: optional(d.sourceId), sourceUrl: optional(d.sourceUrl), embedUrl: optional(d.embedUrl), playbackMode: d.playbackMode as PortfolioContent['playbackMode'], thumbnailUrl: optional(d.thumbnailUrl), thumbnailFileId: optional(d.thumbnailFileId), repositoryUrl: optional(d.repositoryUrl), liveDemoUrl: optional(d.liveDemoUrl), clientName: optional(d.clientName), categories: strings(d.categories), tags: strings(d.tags), technologies: strings(d.technologies), isFeatured: Boolean(d.isFeatured), isPublished: Boolean(d.isPublished), isVisible: d.isVisible !== false, displayOrder: Number(d.displayOrder || 0), publishedAt: optional(d.publishedAt), archivedAt: optional(d.archivedAt), durationSeconds: typeof d.durationSeconds === 'number' ? d.durationSeconds : undefined, showDownloadLink: Boolean(d.showDownloadLink), manualFields: strings(d.manualFields), sourceSnapshot: optional(d.sourceSnapshot) }; }
export async function listPublicContents() { const r = await databases.listDocuments(DATABASE_ID, CONTENTS_COLLECTION_ID, [Query.orderAsc('displayOrder'), Query.orderDesc('$createdAt'), Query.limit(100)]); return r.documents.map((d) => mapContent(d as DocumentData)).filter((v) => v.isPublished && v.isVisible && !v.archivedAt); }
export async function listAdminContents() { const r = await databases.listDocuments(DATABASE_ID, CONTENTS_COLLECTION_ID, [Query.orderAsc('displayOrder'), Query.orderDesc('$updatedAt'), Query.limit(100)]); return r.documents.map((d) => mapContent(d as DocumentData)); }
export async function saveContent(value: ContentInput, id?: string) { const data = { ...value, slug: value.slug || slugify(value.title), publishedAt: value.isPublished ? value.publishedAt || new Date().toISOString() : '', archivedAt: value.archivedAt || '' }; if (id) return databases.updateDocument(DATABASE_ID, CONTENTS_COLLECTION_ID, id, data); return databases.createDocument(DATABASE_ID, CONTENTS_COLLECTION_ID, ID.unique(), data); }
export async function archiveContent(id: string) { return databases.updateDocument(DATABASE_ID, CONTENTS_COLLECTION_ID, id, { archivedAt: new Date().toISOString(), isVisible: false, isPublished: false }); }
export async function updateContentOrder(items: PortfolioContent[]) { await Promise.all(items.map((v, i) => databases.updateDocument(DATABASE_ID, CONTENTS_COLLECTION_ID, v.$id!, { displayOrder: i + 1 }))); }
function mapSettings(d: DocumentData): SiteSettings { return { $id: d.$id, brandName: String(d.brandName || defaultSiteSettings.brandName), contactTitle: String(d.contactTitle || defaultSiteSettings.contactTitle), contactDescription: String(d.contactDescription || defaultSiteSettings.contactDescription), contactEmail: String(d.contactEmail || ''), footerText: String(d.footerText || defaultSiteSettings.footerText) }; }
export async function getSiteSettings() { try { return mapSettings(await databases.getDocument(DATABASE_ID, SETTINGS_COLLECTION_ID, SETTINGS_ID) as DocumentData); } catch { return defaultSiteSettings; } }
export async function saveSiteSettings(value: SiteSettings) { const data = { ...value }; delete data.$id; try { return await databases.updateDocument(DATABASE_ID, SETTINGS_COLLECTION_ID, SETTINGS_ID, data); } catch { return databases.createDocument(DATABASE_ID, SETTINGS_COLLECTION_ID, SETTINGS_ID, data); } }
function mapSocial(d: DocumentData): SocialLink { return { $id: d.$id, label: String(d.label || ''), platform: String(d.platform || ''), url: String(d.url || ''), isVisible: d.isVisible !== false, displayOrder: Number(d.displayOrder || 0) }; }
function mapNav(d: DocumentData): NavigationLink { return { $id: d.$id, label: String(d.label || ''), href: String(d.href || ''), isVisible: d.isVisible !== false, displayOrder: Number(d.displayOrder || 0) }; }
export async function listSocialLinks() { const r = await databases.listDocuments(DATABASE_ID, SOCIAL_LINKS_COLLECTION_ID, [Query.orderAsc('displayOrder'), Query.limit(50)]); return r.documents.map((d) => mapSocial(d as DocumentData)); }
export async function listNavigationLinks() { const r = await databases.listDocuments(DATABASE_ID, NAVIGATION_LINKS_COLLECTION_ID, [Query.orderAsc('displayOrder'), Query.limit(50)]); return r.documents.map((d) => mapNav(d as DocumentData)); }
export async function saveSocialLink(v: SocialLink) { const d = { ...v }; delete d.$id; return v.$id ? databases.updateDocument(DATABASE_ID, SOCIAL_LINKS_COLLECTION_ID, v.$id, d) : databases.createDocument(DATABASE_ID, SOCIAL_LINKS_COLLECTION_ID, ID.unique(), d); }
export async function saveNavigationLink(v: NavigationLink) { const d = { ...v }; delete d.$id; return v.$id ? databases.updateDocument(DATABASE_ID, NAVIGATION_LINKS_COLLECTION_ID, v.$id, d) : databases.createDocument(DATABASE_ID, NAVIGATION_LINKS_COLLECTION_ID, ID.unique(), d); }
export async function deleteSocialLink(id: string) { return databases.deleteDocument(DATABASE_ID, SOCIAL_LINKS_COLLECTION_ID, id); }
export async function deleteNavigationLink(id: string) { return databases.deleteDocument(DATABASE_ID, NAVIGATION_LINKS_COLLECTION_ID, id); }
function mapChannel(d: DocumentData): YouTubeChannel { return { $id: d.$id, $createdAt: d.$createdAt, $updatedAt: d.$updatedAt, name: String(d.name || ''), channelId: String(d.channelId || ''), channelUrl: optional(d.channelUrl), ownerName: optional(d.ownerName), channelType: optional(d.channelType), isActive: d.isActive !== false }; }
export async function listYouTubeChannels() { const r = await databases.listDocuments(DATABASE_ID, YOUTUBE_CHANNELS_COLLECTION_ID, [Query.orderDesc('$updatedAt'), Query.limit(100)]); return r.documents.map((d) => mapChannel(d as DocumentData)); }
export async function saveYouTubeChannel(v: YouTubeChannel) { const d = { ...v }; delete d.$id; delete d.$createdAt; delete d.$updatedAt; return v.$id ? databases.updateDocument(DATABASE_ID, YOUTUBE_CHANNELS_COLLECTION_ID, v.$id, d) : databases.createDocument(DATABASE_ID, YOUTUBE_CHANNELS_COLLECTION_ID, ID.unique(), d); }
export async function deleteYouTubeChannel(id: string) { return databases.deleteDocument(DATABASE_ID, YOUTUBE_CHANNELS_COLLECTION_ID, id); }
