import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { FaGithub, FaYoutube } from 'react-icons/fa';
import { HiExternalLink, HiPlay } from 'react-icons/hi';
import SectionWrapper from './SectionWrapper';
import { listPublicContents } from '../lib/content';
import { safeEmbedUrl, safeExternalUrl } from '../lib/urls';
import type { ContentType, PortfolioContent } from '../types';

const filters: { key: 'all' | ContentType; label: string }[] = [
  { key: 'all', label: 'Tümü' }, { key: 'software_project', label: 'Yazılım' }, { key: 'video_edit', label: 'Video Edit' }, { key: 'personal_video', label: 'Kişisel Video' }, { key: 'client_work', label: 'Müşteri' },
];
const labels: Record<ContentType, string> = { software_project: 'Yazılım Projesi', video_edit: 'Video Edit', personal_video: 'Kişisel Video', client_work: 'Müşteri Çalışması', other: 'Diğer' };
function SourceBadge({ source }: { source: PortfolioContent['sourceType'] }) { const label = source === 'github' ? 'GitHub' : source === 'youtube' ? 'YouTube' : source === 'mega' ? 'MEGA' : source === 'upload' ? 'Yüklenen medya' : 'Manuel'; return <span className="rounded-full border border-white/10 bg-black/30 px-2 py-1 text-[10px] font-semibold text-text-secondary">{label}</span>; }
function ContentCard({ item, index }: { item: PortfolioContent; index: number }) {
  const [playing, setPlaying] = useState(false); const embed = safeEmbedUrl(item.embedUrl); const external = safeExternalUrl(item.sourceUrl || item.repositoryUrl || item.liveDemoUrl);
  const isVideo = item.contentType !== 'software_project';
  return <motion.article initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .4, delay: Math.min(index * .05, .3) }} className="group overflow-hidden rounded-2xl border border-white/5 bg-dark-card/60 transition-all hover:border-neon-purple/30 hover:shadow-xl hover:shadow-neon-purple/10">
    {isVideo && <div className="relative aspect-video overflow-hidden bg-dark-secondary">{playing && embed ? <iframe src={embed} title={item.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen className="absolute inset-0 h-full w-full border-0" /> : <>{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="h-full w-full bg-gradient-to-br from-neon-purple/20 to-neon-blue/10" />}<div className="absolute inset-0 bg-gradient-to-t from-dark/80 to-transparent" />{embed ? <button type="button" onClick={() => setPlaying(true)} className="absolute inset-0 flex items-center justify-center" aria-label={`${item.title} videosunu oynat`}><span className="flex h-14 w-14 items-center justify-center rounded-full bg-neon-purple/90 shadow-lg"><HiPlay className="ml-1 h-6 w-6" /></span></button> : external ? <a href={external} target="_blank" rel="noopener noreferrer" className="absolute inset-0 flex items-center justify-center" aria-label={`${item.title} içeriğini yeni sekmede aç`}><span className="flex h-14 w-14 items-center justify-center rounded-full bg-neon-purple/90 shadow-lg"><HiExternalLink className="h-6 w-6" /></span></a> : null}</>}</div>}
    <div className="p-5"><div className="mb-3 flex items-center justify-between gap-2"><SourceBadge source={item.sourceType} /><span className="text-[10px] text-text-muted">{labels[item.contentType]}</span></div><h3 className="font-heading text-lg font-bold text-white">{item.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-relaxed text-text-secondary">{item.shortDescription || item.description}</p>{item.technologies.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{item.technologies.slice(0, 4).map((tag) => <span key={tag} className="rounded-lg bg-white/5 px-2 py-1 text-xs text-text-muted">{tag}</span>)}</div>}<div className="mt-5 flex gap-3">{safeExternalUrl(item.repositoryUrl) && <a href={safeExternalUrl(item.repositoryUrl)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-text-muted hover:text-white"><FaGithub /> Kaynak</a>}{safeExternalUrl(item.liveDemoUrl) && <a href={safeExternalUrl(item.liveDemoUrl)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-neon-blue hover:text-white"><HiExternalLink /> Demo</a>}{item.sourceType === 'youtube' && <span className="inline-flex items-center gap-1 text-xs text-red-400"><FaYoutube /> Video</span>}</div></div></motion.article>;
}
export default function PortfolioSections() {
  const [items, setItems] = useState<PortfolioContent[]>([]); const [filter, setFilter] = useState<'all' | ContentType>('all'); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  useEffect(() => { listPublicContents().then((data) => { setItems(data); setStatus('ready'); }).catch(() => setStatus('error')); }, []);
  const visible = useMemo(() => items.filter((item) => filter === 'all' || item.contentType === filter), [items, filter]);
  return <section id="projects" className="relative py-24 sm:py-32"><div className="pointer-events-none absolute inset-0"><div className="absolute left-0 top-0 h-px w-full bg-gradient-to-r from-transparent via-neon-purple/20 to-transparent" /></div><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionWrapper><div className="mb-10 text-center"><span className="mb-4 inline-block font-mono text-sm text-neon-purple">{'<Portfolio />'}</span><h2 className="font-heading text-3xl font-bold text-white sm:text-4xl lg:text-5xl">Öne Çıkan <span className="text-gradient-mixed">Çalışmalar</span></h2><p className="mx-auto mt-4 max-w-2xl text-text-secondary">Yazılım projeleri, video editleri ve müşteri çalışmaları.</p></div></SectionWrapper><div className="mb-8 flex flex-wrap justify-center gap-2">{filters.map((item) => <button key={item.key} type="button" onClick={() => setFilter(item.key)} className={`rounded-xl px-4 py-2 text-sm transition-colors ${filter === item.key ? 'bg-neon-purple/20 text-neon-purple neon-border-purple' : 'bg-dark-card text-text-muted hover:text-white'}`}>{item.label}</button>)}</div>{status === 'loading' ? <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-72 animate-pulse rounded-2xl bg-dark-card" />)}</div> : status === 'error' ? <p className="rounded-2xl border border-red-500/20 bg-red-500/10 p-6 text-center text-sm text-red-300">İçerikler şu anda yüklenemedi. Lütfen daha sonra tekrar deneyin.</p> : visible.length ? <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map((item, index) => <ContentCard key={item.$id} item={item} index={index} />)}</div> : <p className="rounded-2xl border border-white/5 bg-dark-card p-10 text-center text-text-muted">Bu kategoride henüz yayımlanmış içerik yok.</p>}</div></section>;
}
